"""empty message

Revision ID: 7247c6d7e3b2
Revises: 07a4a61382d4
Create Date: 2018-11-18 06:44:45.326371

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7247c6d7e3b2'
down_revision = '07a4a61382d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.drop_column('users', 'createdAt')
    op.drop_column('users', 'updatedAt')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('updatedAt', mysql.DATETIME(), nullable=True))
    op.add_column('users', sa.Column('createdAt', mysql.DATETIME(), nullable=True))
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    # ### end Alembic commands ###
